# Generated by Django 4.2 on 2023-08-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('SPORTS', 'SPORTS'), ('CAREER', 'CARRER'), ('SPIRITUAL', 'SPIRITUAL'), ('COMEDY', 'COMEDY'), ('CULTURAL', 'CULTURAL'), ('OTHERS', 'OTHERS')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tag', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='event_details',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='price_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.price_type'),
        ),
    ]
