# Generated by Django 4.2 on 2023-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_event_details_price_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
