# Generated by Django 4.2 on 2023-08-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_event_details_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_details',
            name='price_tag',
        ),
        migrations.AddField(
            model_name='event_details',
            name='price_type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='fixed', max_length=100),
        ),
        migrations.AddField(
            model_name='event_details',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default='fixed', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='category',
            field=models.CharField(choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('SPORTS', 'SPORTS'), ('CAREER', 'CARRER'), ('SPIRITUAL', 'SPIRITUAL'), ('COMEDY', 'COMEDY'), ('CULTURAL', 'CULTURAL'), ('OTHERS', 'OTHERS')], default='fixed', max_length=100),
        ),
    ]
